export const httpBaseUrl = VUE_APP_BASE_API;
const localhttp = 'http://10.148.171.131:8071'
export const jopAdminBaseUrl = `${httpBaseUrl}/jop-admin-web`;
export const jopWXBaseUrl = `${httpBaseUrl}/jop-wx-web`;
export const jopWebBaseUrl = `${httpBaseUrl}/jop-web`;
export const jopCustomerBaseUrl = `${httpBaseUrl}/jop-customer-resource-web`;
export const chatWebBaseUrl = `${httpBaseUrl}/chat-web`;
export const appBaseUrl = `${httpBaseUrl}/app`;
export const jopMarketingWebBaseUrl = `${httpBaseUrl}/jop-marketing-web`;
export const wholesaleBaseUrl = `${httpBaseUrl}/wholesale-web`
export const jopCsrBaseUrl = `${localhttp}/wholesale-web`
export const jopMiniprogramBaseUrl = `${httpBaseUrl}/jip-admin-web`
